// Saytdagi barcha matnlar (o‘zbek, lotin). Narx, muddat, telefon kabi qiymatlar — src/config.js da.

export const T = {
  nav: { about: 'RUTIM haqida', calc: 'Kalkulyator', products: 'Katalog', faq: 'Savollar', cta: 'Diler narxlarini olish' },
  hero: {
    eyebrow: 'Do‘kon egalari uchun',
    title1: 'Stabilizatorlarni diler narxida oling —',
    title2: 'har bir sotuvdan foyda qiling',
    lead: 'Qish yaqin: svet o‘chishi va kuchlanish sakrashi bilan stabilizatorga talab oshadi. Do‘koningizda RUTIM bo‘lsin.',
    badges: ['Diler narxi', '60 kunlik almashtirish kafolati', 'Bepul yetkazish'],
    cta: 'Diler narxlarini olish',
    telegram: 'Telegram orqali yozish',
    monitorTitle: 'Tarmoq monitori',
    monitorIn: 'Kirish',
    monitorOut: 'Chiqish',
    monitorCaption: 'Tarmoq sakraydi. Texnika — himoyada.',
  },
  about: {
    kicker: 'RUTIM haqida',
    title: 'RUTIM — kuchlanish stabilizatorlari brendi',
    lead: 'RUTIM bir fazali kuchlanish stabilizatorlarini Xitoydan to‘g‘ridan-to‘g‘ri import qiladi va O‘zbekiston bo‘ylab do‘konlarga diler narxida yetkazib beradi. Kafolat servisi — RUTIM’ning o‘zida.',
    stats: [
      { v: '18', l: 'model' },
      { v: '3', l: 'seriya' },
      { v: '500 VA – 30 kVA', l: 'quvvat oralig‘i' },
      { v: '45 V', l: 'dan ishlaydi (RRC45)' },
    ],
    power: 'Quvvat',
    input: 'Kirish',
    output: 'Chiqish',
    models: 'model',
    see: 'Modellarni ko‘rish',
    ctaText: 'Barcha seriyalar diler narxida — do‘koningiz uchun narxlar ro‘yxatini oling.',
    cta: 'Diler narxlarini olish',
  },
  calc: {
    kicker: 'Foyda kalkulyatori',
    title: 'Bitta stabilizatordan qancha ishlaysiz?',
    lead: 'Modelni va oyiga nechta sotishingizni tanlang — foydangizni darhol ko‘rasiz.',
    model: 'Model',
    units: 'Oyiga sotuv',
    unitsSuffix: 'dona',
    dealer: 'Diler narxi',
    retail: 'Tavsiya etilgan chakana narx',
    perUnit: 'Bir donadan foyda',
    monthly: 'Oylik foyda',
    onRequest: 'Narxlar so‘rov bo‘yicha',
    onRequestText: 'Ushbu model uchun diler va chakana narxni menejer aytadi — foydangizni birga hisoblaymiz.',
    cta: 'Shu model narxini olish',
    note: 'Hisob taxminiy: chakana narxni o‘zingiz belgilaysiz.',
  },
  risk: {
    title: 'Sotilmay qolishidan qo‘rqasizmi?',
    text: '60 kun ichida sotilmagan modelni boshqa modelga almashtirib beramiz. Qolib ketgan tovar muammosi yo‘q.',
    badge: '60 kun',
    badgeSub: 'almashtirish kafolati',
  },
  why: {
    kicker: 'Nega RUTIM',
    title: 'Do‘kon uchun qulay hamkor',
    items: [
      { icon: 'ship', t: 'Xitoydan to‘g‘ridan-to‘g‘ri import', d: 'Vositachisiz narx' },
      { icon: 'shield', t: 'Kafolat servisi bizda', d: 'Buzilsa, siz ovora bo‘lmaysiz' },
      { icon: 'truck', t: 'Bepul yetkazish', d: 'O‘zbekiston bo‘ylab' },
      { icon: 'stand', t: 'Bepul stend, banner va narx yorliqlari', d: 'Peshtaxtangiz tayyor bo‘ladi' },
      { icon: 'gift', t: 'Qayta buyurtmada bonus', d: 'Har safar ko‘proq foyda' },
      { icon: 'bolt', t: '18 model', d: '500 VA dan 30 kVA gacha' },
    ],
  },
  segment: {
    title: 'Kotel yoki konditsioner sotasizmi?',
    text: 'Har bir kotel va konditsionerga stabilizator taklif qiling — o‘rtacha chekingiz oshadi.',
    cta: 'Diler narxlarini olish',
  },
  products: {
    kicker: 'Katalog',
    title: '18 model — har bir mijozga mos',
    lead: '500 VA dan 30 kVA gacha. Rasmni bosing — barcha rasmlar va xususiyatlarini ko‘rasiz.',
    price: 'Diler narxi — so‘rov bo‘yicha',
    cta: 'Narxini bilish',
    fitFor: 'Kimga',
  },
  fit: {
    s: 'Muzlatgich, TV, kompyuter',
    m: 'Konditsioner, kir yuvish mashinasi',
    l: 'Butun kvartira yoki ofis',
    xl: 'Hovli uy, ustaxona, sex',
  },
  series: {
    RRC95: { tag: 'Universal', type: 'Relelik', short: 'Eng ommabop seriya: xonadon, ofis va do‘konlar uchun. LED displey va Bypass rejimi.' },
    RRC45: { tag: 'Past kuchlanish', type: 'Relelik', short: 'Kuchlanish juda past tushadigan hududlar uchun — 45 V dan ishlaydi, FIK 95% dan yuqori.' },
    RTC: { tag: 'Aniq ±5%', type: 'Avtomatik (AVR)', short: 'Sezgir texnika va ishlab chiqarish uskunalari uchun: aniq chiqish va qizib ketishdan himoya.' },
  },
  specs: {
    type: 'Turi',
    power: 'Quvvat',
    input: 'Kirish kuchlanishi',
    output: 'Chiqish kuchlanishi',
    display: 'Displey',
    displayV: 'Raqamli LED',
    bypass: 'Bypass rejimi',
    bypassV: 'Bor',
    protection: 'Himoya',
    protect: {
      RRC95: ['Yuqori kuchlanish', 'Past kuchlanish', 'Ortiqcha yuklama', 'Qisqa tutashuv'],
      RRC45: ['Yuqori va past kuchlanish', 'Ortiqcha yuklama', 'Qisqa tutashuv'],
      RTC: ['Yuqori kuchlanish', 'Past kuchlanish', 'Ortiqcha yuklama', 'Qisqa tutashuv', 'Qizib ketish'],
    },
  },
  modal: { close: 'Yopish', note: 'Diler narxi — so‘rov bo‘yicha' },
  reviews: {
    kicker: 'Fikrlar',
    title: 'Hamkor do‘konlar',
  },
  faq: {
    kicker: 'Savollar',
    title: 'Ko‘p beriladigan savollar',
    // c — src/config.js dagi CONFIG (minOrder, deliveryTime, warranty). Qiymat bo‘sh bo‘lsa, javob usiz chiqadi.
    items: [
      {
        q: 'Minimal buyurtma qancha?',
        a: (c) => (c.minOrder ? `${c.minOrder}. Aniq shartlarni menejer aytadi.` : 'Minimal buyurtma miqdorini menejer aytadi.'),
      },
      {
        q: 'Nasiya yoki sotuvdan keyin to‘lov bormi?',
        a: () => 'Yo‘q, xarid oldindan to‘lov asosida. Buning evaziga diler narxi va 60 kunlik almashtirish kafolatini beramiz.',
      },
      { q: 'Almashtirish qanday ishlaydi?', a: () => '60 kun ichida sotilmagan modelni boshqa modelga almashtiramiz.' },
      {
        q: 'Yetkazish qancha vaqt oladi?',
        a: (c) => (c.deliveryTime ? `${c.deliveryTime}, O‘zbekiston bo‘ylab bepul.` : 'O‘zbekiston bo‘ylab bepul.'),
      },
      {
        q: 'Kafolat qanday?',
        a: (c) => (c.warranty ? `${c.warranty} kafolat, servisni RUTIM o‘zi qiladi.` : 'Rasmiy kafolat, servisni RUTIM o‘zi qiladi.'),
      },
    ],
  },
  lead: {
    title: 'Diler narxlari va katalogni oling',
    sub: 'Menejerimiz 1 soat ichida qo‘ng‘iroq qiladi',
    perks: ['Barcha 18 model diler narxlari', 'Yetkazish va kafolat shartlari', 'Qayta buyurtma bonuslari'],
    model: 'Model',
    name: 'Ism',
    namePh: 'Masalan, Aziz',
    phone: 'Telefon',
    city: 'Shahar / viloyat',
    shopType: 'Do‘kon turi',
    shopTypes: ['Elektr tovarlar', 'Maishiy texnika', 'Kotel-konditsioner', 'Qurilish bozori', 'Boshqa'],
    choose: 'Tanlang',
    submit: 'Narxlarni olish',
    sending: 'Yuborilmoqda…',
    consent: 'Tugmani bosib, siz bilan telefon orqali bog‘lanishimizga rozilik bildirasiz.',
    errName: 'Ismingizni kiriting',
    errPhone: 'Raqamni to‘liq kiriting: +998 XX XXX XX XX',
    errCity: 'Shahar yoki viloyatni tanlang',
    fail: 'Ariza yuborilmadi. Internetni tekshirib, qayta bosing.',
    failCall: 'Yoki qo‘ng‘iroq qiling:',
    okTitle: 'Rahmat! Tez orada bog‘lanamiz.',
    okText: 'Menejer {phone} raqamiga qo‘ng‘iroq qiladi.',
    okAgain: 'Yana ariza qoldirish',
  },
  footer: {
    about: 'RUTIM electric — bir fazali kuchlanish stabilizatorlari. Do‘konlar uchun diler narxlari.',
    inn: 'STIR',
    rights: 'Barcha huquqlar himoyalangan.',
  },
}
